In [30]:
import pandas as pd
import numpy as np

In [23]:
"Question 1: What version of Pandas did you install?"
pd.__version__

'2.3.1'

In [9]:
"Question 2: How many records are in the dataset?"
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [10]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [12]:
"Question 3: How many fuel types are presented in the dataset?"
df.fuel_type.nunique()

2

In [13]:
"Question 4: How many columns in the dataset have missing values?"
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [16]:
"Question 5: What's the maximum fuel efficiency of cars from Asia?"
df[(df.origin == 'Asia')].sort_values(by='fuel_efficiency_mpg', ascending=False)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
9387                  330            3.0       136.0     1223.298226   
343                   240            2.0         NaN     1652.883753   
7739                  170           10.0       139.0     1491.755825   
9401                  110            1.0       183.0     1707.231276   
5416                  250            6.0       173.0     1354.787120   
...                   ...            ...         ...             ...   
2890                  240            4.0        92.0     4323.711871   
9120                  180            3.0       181.0     4661.144932   
6581                  150            NaN       148.0     4392.759292   
3891                  290            6.0       145.0     4481.764226   
1095                  210            6.0        93.0     4345.732510   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
9387           NaN        2001   Asia  Gasoline  Front-wheel drive        1.0   
343           11.0        2018   Asia  Gasoline  Front-wheel drive        0.0   
7739          13.0        2005   Asia    Diesel  Front-wheel drive        0.0   
9401          11.9        2018   Asia    Diesel    All-wheel drive       -1.0   
5416          17.3        2007   Asia  Gasoline  Front-wheel drive        0.0   
...            ...         ...    ...       ...                ...        ...   
2890          14.8        2007   Asia    Diesel    All-wheel drive       -1.0   
9120          12.5        2004   Asia    Diesel  Front-wheel drive        0.0   
6581          17.1        2016   Asia    Diesel    All-wheel drive        1.0   
3891          17.4        2010   Asia  Gasoline    All-wheel drive        0.0   
1095          18.9        2021   Asia    Diesel    All-wheel drive        0.0   

      fuel_efficiency_mpg  
9387            23.759123  
343             23.204566  
7739            23.033673  
9401            22.919968  
5416            22.858156  
...                   ...  
2890             7.485553  
9120             7.329314  
6581             7.317353  
3891             6.939508  
1095             6.886245  

[3247 rows x 11 columns]

In [17]:
"""
Question 6:
1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.
Has it changed?
"""
#Median value of horse power is 149
df['horsepower'].median()

np.float64(149.0)

In [18]:
#Mode of horse power is 152
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [37]:
#fill every missing value of horsepower column with its median
df['horsepower'].fillna(df['horsepower'].median())

0       159.0
1        97.0
2        78.0
3       149.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [21]:
#check median, no change
df['horsepower'].median()

np.float64(149.0)

In [26]:
"""
Question 7:
1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?
"""
#Select all cars from Asia
asia_df = df[(df.origin == 'Asia')]
asia_df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       149.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [28]:
#Select only columns vehicle_weight and model_year
asia_df[['vehicle_weight', 'model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [31]:
#select the first 7 values
new_df = asia_df[['vehicle_weight', 'model_year']].head(7)
new_df

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [34]:
#Convert to numpy array matrix
x = new_df.to_numpy()
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [40]:
# transpose matrix and multiply it by itself
xt = x.T
xtx = np.dot(xt, x)
xtx

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [42]:
#invert matrix xtx
xtx = np.linalg.inv(xtx)
xtx

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [43]:
#Create array y with values
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [45]:
#Multiply inverse of xtx with transpose of x then multiply results by y, call it w
w = np.dot(xtx, xt) * y
w

array([[-0.14432288, -0.11230828,  0.29810794, -0.36245398, -0.16251372,
        -0.06075771,  0.55811286],
       [ 0.28890053,  0.2560879 , -0.37871378,  0.59305003,  0.30835783,
         0.16679975, -0.72957556]])

In [46]:
#What's the sum of all the elements? we have just sucessfully implemented linear regression
w.sum()

np.float64(0.5187709081074016)